### PR TITLE
fix(execute): check stream equality

### LINKED ISSUE #2893: Verify correctness of table streams regardless of table and column order
Table streams with equivalent data, but differing column and/or table orders should be considered equal. We currently have test helpers that do not correctly check that streams are the same regardless of column/table order.

This is possibly causing flakiness in tests across the flux repo and in our pipeline tests. 

The following functions need to be updated to do this. 

EqualResultIterators: https://github.com/influxdata/flux/blob/745073a0c2558ad023b01aba41172c87fd354c45/execute/executetest/result.go#L85
EqualResult: https://github.com/influxdata/flux/blob/745073a0c2558ad023b01aba41172c87fd354c45/execute/executetest/result.go#L128
NormalizeTables: https://github.com/influxdata/flux/blob/745073a0c2558ad023b01aba41172c87fd354c45/execute/executetest/table.go#L479

Since EqualResult and EqualResultIterators read the entire table stream into memory, we can just updated NormalizeTables to sort the result. 

NormalizeTables needs to be updated to call two functions: one that will sort tables by group key and another that will sort each table's columns in a consistent order.  

NOTE: This might not be efficient for tests that return a big result.

### PR DESCRIPTION
**Pull request by fchikwekwe**
Closes #2893. 

Previously table stream checked with `NormalizeTables()` were only registering as equal when both the tables and columns were in the exact same order. This PR will put tables and columns in a consistent order so that they can be properly checked for equality.

### CODE REVIEW

File: execute/executetest/table.go [hunk 1]
```diff
@@ -480,6 +481,88 @@ func NormalizeTables(bs []*Table) {
...
+func sortByGroupKey(tables []*Table) []*Table {
+	if len(tables) < 2 {
+		return tables
+	}
+
+	for _, table := range tables {
+		// somehow this line makes the test pass
+		// no idea why
+		_ = table.Key().String()
+	}
```
Comment (fchikwekwe) [inline execute/executetest/table.go:498]: I'm not sure why, but removing this for loop causes `TestNormalizeTables()` to fail. Any ideas?

File: execute/executetest/table.go [hunk 2]
```diff
@@ -480,6 +481,88 @@ func NormalizeTables(bs []*Table) {
 	for _, b := range bs {
 		b.Key()
 	}
+	bs = sortByGroupKey(bs)
+}
+
+// sortByGroupKey uses recursive quicksort to sort the tables by group key
+// in alphabetical order
```
Comment (fchikwekwe) [inline execute/executetest/table.go:488]: Implemented two different versions of quick sort for this PR. I used recursive quick sort for table order, since the tables were easy to reorder independently. And I used iterative quick sort for column order, since columns need to be updated per table, it was easier to keep track of them using a stack.

File: csv/result_test.go [hunk 3]
```diff
@@ -30,198 +30,21 @@ type TestCase struct {
 	encoderConfig csv.ResultEncoderConfig
 }
 
-var symmetricalTestCases = []TestCase{
```
Comment (fchikwekwe) [inline csv/result_test.go:33]: Test cases were not being normalized from this array. Moved them into the respective test functions.

File: execute/executetest/table.go [hunk 4]
```diff
@@ -475,11 +476,58 @@ func (b SortedTables) Swap(i int, j int) {
...
+	}
+}
+
+func sortColumns(table *Table) {
+	// index reference to make sure that sort is consistent for metadata and data
+	indexes := createReferenceArray(table)
+
+	columnsCopy := make([]flux.ColMeta, len(table.ColMeta))
+	for i, value := range indexes {
+		columnsCopy[i] = table.ColMeta[value]
```
Comment (rockstar) [inline execute/executetest/table.go:501]: Does `copy` not do this for us?

File: execute/executetest/table.go [hunk 5]
```diff
@@ -475,11 +476,58 @@ func (b SortedTables) Swap(i int, j int) {
...
+	}
+	table.ColMeta = columnsCopy
+
+	// don't create a new table.Data if there is no Data
+	if len(table.Data) == 0 {
+		return
+	}
+	valuesCopy := make([][]interface{}, len(table.Data))
```
Comment (rockstar) [inline execute/executetest/table.go:509]: Do we need to make a full `valuesCopy`? Can we get away with just copying the row as we need it, since we're not re-ordering the rows themselves?

Comment (fchikwekwe) [reply execute/executetest/table.go:509]: We still need the outer array to house the interface array.

File: execute/executetest/table.go (hunk 4 above)
Comment (fchikwekwe) [reply execute/executetest/table.go:501]: No, the copy doesn't populate the map with the required values. For some reason, the `copy` function doesn't play well with `flux.ColMeta` values.

Comment (rockstar) [reply execute/executetest/table.go:501]: Could you add a comment to that effect? I can see myself seeing that one day and thinking "why is this like this?" and trying to simplify it. Luckily, we'll have a failing test as a result, but the _why_ would be super helpful.

Comment (fchikwekwe) [reply execute/executetest/table.go:502]: Comment added.
