### PR TITLE
bug(options): Add key instead of erroring when option doesn't have key

### LINKED ISSUE #974: Options Editor doesn't allow inserting of option keys that don't already exist in the option.
Options Editor doesn't allow inserting of option keys that don't already exist in the option.

Instead it errors with: cannot find property 'offset' in object expression

https://github.com/influxdata/influxdb/issues/11324

### PR DESCRIPTION
**Pull request by docmerlin**
This adds a key to options if the key doesn't already exist in the option instead of erroring.
Closes #974 
### Done checklist
- [x ] Test cases written

### CODE REVIEW

File: ast/edit/option_editor.go [hunk 1]
```diff
@@ -51,14 +51,17 @@ func OptionObjectFn(keyMap map[string]ast.Expression) OptionFn {
...
+		found := make(map[string]bool, len(obj.Properties))
 		for _, p := range obj.Properties {
-			keys[p.Key.Key()] = true
+			found[p.Key.Key()] = false
 		}
 
 		for k := range keyMap {
-			if !keys[k] {
-				return nil, fmt.Errorf("cannot find property '%s' in object expression", k)
+			if _, ok := found[k]; !ok {
```
Comment (nathanielc) [inline ast/edit/option_editor.go]: Nit, this should be simplified to `if !found[k] {`

**Comment by docmerlin** [comment]
Thanks @affo, doh
