### PR TITLE
fix(length): removes unnecessary TableObject guards

### LINKED ISSUE #4343: Remove TableObject type assertion guards
This work will remove guards that check to see if a `Value` is a `TableObject` just before we make an attempt to invoke the `Array.Len()`. 

Once we after we are able to properly represent `TableObject`s separately from standard `array` objects, the type assertions should be redundant. At that point, hopefully both the compiler and humans will be able to tell the difference between these two types.

### PR DESCRIPTION
**Pull request by nathanielc**
Now that the type system can distinguish between streams (aka tables)
and vanilla arrays we no longer need the TableObject interface and its
associated type guards.

Fixes #4343

### Done checklist
- [ ] docs/SPEC.md updated
- [x] Test cases written

### CODE REVIEW

File: stdlib/universe/join.go [hunk 1]
```diff
@@ -81,10 +81,6 @@ func createJoinOpSpec(args flux.Arguments, a *flux.Administration) (flux.Operati
 	if array, err := args.GetRequiredArray("on", semantic.String); err != nil {
 		return nil, err
 	} else if _, ok := array.(values.TableObject); ok {
-		// XXX: remove when array/stream are different types <https://github.com/influxdata/flux/issues/4343>
-		return nil, errors.New(codes.Invalid, "on cannot be a table stream; expected an array")
-	} else if array.Len() == 0 {
-		return nil, errors.New(codes.Invalid, "at least one column in 'on' column list is required")
```
Comment (nathanielc) [inline stdlib/universe/join.go:87]: fixing this...

Comment (nathanielc) [reply stdlib/universe/join.go:87]: fixed

**Review by onelson — APPROVED** [review]
Looks great. Cheers!

big-red
