### PR TITLE
fix(interpreter|repl): make repl output every side effect of the line…

### LINKED ISSUE #1234: Script returns partial results on multiple yields
On system stats written by telegraf:

```
y = () => from(bucket: "Default")
	|> range(start: -5m)
	|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system" and r.cpu == "cpu-total")
    |> yield(name: "y")

x = () => from(bucket: "Default")
	|> range(start: -5m)
	|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system" and r.cpu == "cpu-total")
	|> map(fn: (r) => ({_time: r._time, index: 1}))
	|> cumulativeSum(columns: ["index"])
    |> yield(name: "x")

x()
y()
```

I get:

```
Result: y
Table: keys: [_start, _stop, _field, _measurement, cpu, host]
                   _start:time                      _stop:time           _field:string     _measurement:string              cpu:string             host:string                      _time:time                  _value:float  
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------  
2019-05-03T09:59:41.865336000Z  2019-05-03T10:04:41.865336000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T09:59:45.000000000Z            1.2256128064032017  
2019-05-03T09:59:41.865336000Z  2019-05-03T10:04:41.865336000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T09:59:55.000000000Z             1.374656335916021  
2019-05-03T09:59:41.865336000Z  2019-05-03T10:04:41.865336000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:00:05.000000000Z             1.750291715285881  
2019-05-03T09:59:41.865336000Z  2019-05-03T10:04:41.865336000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:00:15.000000000Z            1.3333333333333333  
2019-05-03T09:59:41.865336000Z  2019-05-03T10:04:41.865336000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:00:25.000000000Z            1.6831930672443962  
2019-05-03T09:59:41.865336000Z  2019-05-03T10:04:41.865336000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:00:35.000000000Z            1.3496625843539116  
2019-05-03T09:59:41.865336000Z  2019-05-03T10:04:41.865336000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:00:45.000000000Z            1.2167680640053338  
...
```
Only `y` instead of `x` and `y`.

If I swap `x()` and `y()` in the original script I get only `x`.

If I change the script to:

```
y = () => from(bucket: "Default")
	|> range(start: -5m)
	|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system" and r.cpu == "cpu-total")
    |> yield(name: "y")

x = () => from(bucket: "Default")
	|> range(start: -5m)
	|> filter(fn: (r) => r._measurement == "cpu" and r._field == "usage_system" and r.cpu == "cpu-total")
	|> map(fn: (r) => ({_time: r._time, index: 1}))
	|> cumulativeSum(columns: ["index"])
    |> yield(name: "x")

joined = () => join(tables: {x: x(), y: y()}, on: ["_time"]])

joined()
```

I get:

```
Result: x
Table: keys: [_start, _stop, _field, _measurement, cpu, host]
                   _start:time                      _stop:time           _field:string     _measurement:string              cpu:string             host:string                      _time:time                   index:int  
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  --------------------------  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:03:45.000000000Z                           1  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:03:55.000000000Z                           2  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:04:05.000000000Z                           3  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:04:15.000000000Z                           4  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:04:25.000000000Z                           5  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:04:35.000000000Z                           6  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:04:45.000000000Z                           7  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:04:55.000000000Z                           8  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:05:05.000000000Z                           9  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:05:15.000000000Z                          10  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:05:25.000000000Z                          11  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:05:35.000000000Z                          12  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:05:45.000000000Z                          13  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:05:55.000000000Z                          14  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:06:05.000000000Z                          15  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:06:15.000000000Z                          16  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:06:25.000000000Z                          17  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:06:35.000000000Z                          18  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:06:45.000000000Z                          19  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:06:55.000000000Z                          20  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:07:05.000000000Z                          21  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:07:15.000000000Z                          22  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:07:25.000000000Z                          23  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:07:35.000000000Z                          24  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:07:45.000000000Z                          25  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:07:55.000000000Z                          26  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:08:05.000000000Z                          27  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:08:15.000000000Z                          28  
2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z            usage_system                     cpu               cpu-total                 macbook  2019-05-03T10:08:25.000000000Z                          29  
Result: y
Table: keys: [_start, _stop, _field, _measurement, cpu, host]
                   _start:time                      _stop:time           _field:string     _measurement:string              cpu:string             host:string                      _time:time                  _value:float  
------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------  
Result: _result
Table: keys: [_field_x, _field_y, _measurement_x, _measurement_y, _start_x, _start_y, _stop_x, _stop_y, cpu_x, cpu_y, host_x, host_y]
       _field_x:string         _field_y:string   _measurement_x:string   _measurement_y:string                   _start_x:time                   _start_y:time                    _stop_x:time                    _stop_y:time            cpu_x:string            cpu_y:string           host_x:string           host_y:string                      _time:time                  _value:float                   index:int  
----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ------------------------------  ------------------------------  ------------------------------  ----------------------  ----------------------  ----------------------  ----------------------  ------------------------------  ----------------------------  --------------------------  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:03:45.000000000Z            3.8663444712940587                           1  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:03:55.000000000Z            1.3420021672084688                           2  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:04:05.000000000Z            1.5419236539423238                           3  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:04:15.000000000Z            1.4502417069511586                           4  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:04:25.000000000Z            1.1833333333333333                           5  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:04:35.000000000Z            1.0500875072922744                           6  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:04:45.000000000Z            1.3323340827712549                           7  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:04:55.000000000Z            1.6264909500375344                           8  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:05:05.000000000Z             2.299042065805914                           9  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:05:15.000000000Z            2.5235279420338137                          10  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:05:25.000000000Z            1.5757878939469734                          11  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:05:35.000000000Z            1.1163875697742232                          12  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:05:45.000000000Z             1.350337584396099                          13  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:05:55.000000000Z            1.4666666666666666                          14  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:06:05.000000000Z             1.433452787732311                          15  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:06:15.000000000Z             2.124468882779305                          16  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:06:25.000000000Z             1.833638939823304                          17  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:06:35.000000000Z            1.4998750104157987                          18  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:06:45.000000000Z             2.016834736228019                          19  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:06:55.000000000Z            1.6752792132022003                          20  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:07:05.000000000Z             1.849691718046992                          21  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:07:15.000000000Z             2.008500708392366                          22  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:07:25.000000000Z            1.6747208798533577                          23  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:07:35.000000000Z            1.5748687609365886                          24  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:07:45.000000000Z             1.767403084618591                          25  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:07:55.000000000Z            1.3995334888370543                          26  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:08:05.000000000Z            1.2746813296675832                          27  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:08:15.000000000Z             1.350225037506251                          28  
          usage_system            usage_system                     cpu                     cpu  2019-05-03T10:03:38.611196000Z  2019-05-03T10:03:38.611196000Z  2019-05-03T10:08:38.611196000Z  2019-05-03T10:08:38.611196000Z               cpu-total               cpu-total                 macbook                 macbook  2019-05-03T10:08:25.000000000Z             2.200366727787965                          29  
```

So, `x` and empty `y` (even if it is not empty), and the result of `joined()`.

Results are retrieved by using `influx` command. E.g.:

```
./bin/darwin/influx query @buggy.flux --org root
```

### PR DESCRIPTION
**Pull request by affo**
… under evaluation

This partially solves #1234, in that it solves the issue of not getting some piece of results.  
It doesn't fix the issue of empty tables returned, though. I couldn't reproduce that in Flux, so it could be caused by InfluxDB.

This also updates `flux execute` to use the REPL.

The REPL can pass multiple lines at once to the interpreter (for example, when loading a file). This makes it limiting to only consume `scope.Return()`, because the script under evaluation could produce multiple side effects. I updated the interpreter to return `Eval`-local side effects (as opposed to every possible side effects occurred in multiple calls to `Eval`), and updated the data structure that contains a side effectsto contain also the `semantic.Node` that generated it. In this way, the REPL can filter out which side effect to display on standard out.

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

### CODE REVIEW

File: interpreter/interpreter.go [hunk 1]
```diff
@@ -56,9 +68,13 @@ func (itrp *Interpreter) Eval(node semantic.Node, scope Scope, importer Importer
 		}
 	}), node)
 
+	// reset side effect list
+	itrp.sideEffects = make([]SideEffect, 0)
 	if err := itrp.doRoot(node, scope, importer); err != nil {
 		return nil, err
 	}
+	// update global side effects
+	itrp.globalSideEffects = append(itrp.globalSideEffects, itrp.sideEffects...)
```
Comment (jlapacik) [inline interpreter/interpreter.go]: Perhaps you wanted to update the global side effects before you reset the local one? As it stands right now, you'd be appending an empty array to the global side effects.

File: repl/repl.go [hunk 2]
```diff
@@ -113,74 +113,68 @@ func (r *REPL) completer(d prompt.Document) []prompt.Suggest {
...
-		return nil, err
+		return err
 	}
 
-	v := r.scope.Return()
-
-	// Ignore statements that do not return a value
-	if v == nil {
-		return nil, nil
+	ses, err := r.interpreter.Eval(semPkg, r.scope, flux.StdLib())
```
Comment (jlapacik) [inline repl/repl.go]: I think you can condense this line and the lines above into a single call to `flux.Eval(t)`.

File: interpreter/interpreter.go [hunk 3]
```diff
@@ -11,10 +11,11 @@ import (
...
 
 type Interpreter struct {
-	types       map[semantic.Node]semantic.Type
-	polyTypes   map[semantic.Node]semantic.PolyType
-	sideEffects []values.Value
-	pkg         string
+	types             map[semantic.Node]semantic.Type
+	polyTypes         map[semantic.Node]semantic.PolyType
+	sideEffects       []SideEffect // a list of the side effects occurred during the last call to `Eval`.
+	globalSideEffects []SideEffect // a list of every side effect occurred within multiple evaluations.
```
Comment (jlapacik) [inline interpreter/interpreter.go]: Is this field necessary? Only the repl calls Eval multiple times, but I believe it only cares about the side effects produced from the last call.

File: interpreter/interpreter.go [hunk 4]
```diff
@@ -56,9 +68,13 @@ func (itrp *Interpreter) Eval(node semantic.Node, scope Scope, importer Importer
 		}
 	}), node)
 
+	// reset side effect list
+	itrp.sideEffects = make([]SideEffect, 0)
```
[the remark this answers is not in the document]
Comment (affo) [reply interpreter/interpreter.go]: Looks way better :)

File: interpreter/interpreter.go (hunk 1 above)
Comment (affo) [reply interpreter/interpreter.go]: Mmmm 🤔 , I don't think so. Tests pass successfully, indeed.

`doRoot` updates local side effects.

File: interpreter/interpreter.go (hunk 3 above)
Comment (affo) [reply interpreter/interpreter.go]: That's fine, I wanted to preserve somehow the previous behavior.

**Comment by affo** [comment]
> Can you explain a little bit how this fixes #1234?

@jlapacik You are definitely right. I only fixed the first problem, but I didn't even reproduced the second one. I'll add more work to this and ping you once I get it done.

**Comment by affo** [comment]
@jlapacik I updated the code and edited the comment above, so that it doesn't close the issue.
