### PR TITLE
fix: Propagate the element type through array constructors

### LINKED ISSUE #3858: Static type for array.from() causing strange output from findColumn
The following query yields: `cannot represent the type t11447 as column data`

```
  getValue = (b, me, f) => {
    r = from(bucket: b)
    |> range(start: -99d)
    |> filter(fn: (r) => r["_measurement"] == me)
    |> group(columns: ["_field"])
    |> first()
    |> aggregateWindow(every: 1s, fn: last, createEmpty: false)
    |> yield(name: "last")
    |> findColumn(
            fn: (key) => (key._field == f),
            column: "_value"
    )
    return r[0]
    }
scalar =  getValue(b:"noaa",me:"average_temperature",f:"degrees" )

array.from(rows: [{_time: now(), _value: scalar}])
|>yield(name:"test value")

from(bucket: "noaa")
	|> range(start: -30d)
	|> filter(fn: (r) => (r["_field"] == "degrees"))
	|> set(key: "_measurement", value: "scaledMeasurements")
    |> limit(n: 5)
	|> map(fn: (r) =>
		({r with _value: scalar}))
  |> yield(name:"complete")
```

Output:
```
#group,false,false,true,true,false,false,true,false,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string
#default,last,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,location
,,0,2021-03-30T16:00:05.180856426Z,2021-07-07T16:00:05.180856426Z,2021-05-14T21:11:38Z,74,degrees,average_temperature,santa_monica
#group,true,true
#datatype,string,string
#default,,
,error,reference
,cannot represent the type t11454 as column data,
```

Solution 
```
 return float(v:r[0])
```

### PR DESCRIPTION
**Pull request by Marwes**
Before it was just using the statically determined type which causes functions like `array.from` to fail as they would see the type variable from the generic function instead of the actual type.

Fixes #3858

### Done checklist
- [x] Test cases written

### CODE REVIEW

File: stdlib/array/flux_test_gen.go [hunk 1]
```diff
@@ -3077,2878 +3077,6 @@ var FluxTestPackages = []*ast.Package{&ast.Package{
 				Name: "array_test",
 			},
 		},
-	}, &ast.File{
```
Comment (Marwes) [inline stdlib/array/flux_test_gen.go:3080]: This doesn't seem right  I just added to the file:S

**Review by wolffcm — APPROVED** [review]
This looks fine, but I wonder if the code that was producing the message `cannot represent the type t11447 as column data` was looking in the wrong place for the type. I guess this will be part of the discussion next week about "runtime values should not know their type".

**Comment by Marwes** [comment]
Arguably, yes. But if we decided that it should not be looking at the `MonoType` stored in the value as it currently does, we ought to remove the stored `MonoType` entirely since it can't be reasonably correct.
