### PR TITLE
fix(control): refactor the controller to remove data races

### LINKED ISSUE #928: Data race when cancelling a query
Filing this here in the flux repo, but I observed a data race in the query controller when shutting down influxd (influxdb commit bd3c9cc75cbb38aad54aae23f39bfe6df32875b4 using flux v0.17.0):

```
==================
WARNING: DATA RACE
Write at 0x00c0010d2120 by goroutine 81:
  github.com/influxdata/flux/control.(*Query).transitionTo()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:606 +0x159
  github.com/influxdata/flux/control.(*Query).Cancel()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:518 +0x118
  github.com/influxdata/influxdb/task/backend/executor.(*asyncRunPromise).followQuery()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/executor/executor.go:286 +0x524

Previous read at 0x00c0010d2120 by goroutine 83:
  github.com/influxdata/flux/control.(*Controller).processQuery()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:424 +0x29e
  github.com/influxdata/flux/control.(*Controller).run()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:344 +0x3e9

Goroutine 81 (running) created at:
  github.com/influxdata/influxdb/task/backend/executor.newAsyncRunPromise()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/executor/executor.go:252 +0x580
  github.com/influxdata/influxdb/task/backend/executor.(*asyncQueryServiceExecutor).Execute()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/executor/executor.go:215 +0x360
  github.com/influxdata/influxdb/task/backend.(*runner).executeAndWait()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/scheduler.go:636 +0x1b7

Goroutine 83 (running) created at:
  github.com/influxdata/flux/control.New()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:106 +0x624
  github.com/influxdata/influxdb/cmd/influxd/launcher.(*Launcher).run()
      /Users/mr/go/src/github.com/influxdata/influxdb/query/control/controller.go:25 +0x2d08
  github.com/influxdata/influxdb/cmd/influxd/launcher.(*Launcher).Run.func1()
      /Users/mr/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:179 +0x53
  github.com/influxdata/influxdb/kit/cli.NewCommand.func1()
      /Users/mr/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:51 +0x55
  github.com/spf13/cobra.(*Command).execute()
      /Users/mr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x527
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/mr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x3ed
  github.com/influxdata/influxdb/cmd/influxd/launcher.(*Launcher).Run()
      /Users/mr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0xb0b
  main.main()
      /Users/mr/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:32 +0x58d
==================
```

Here's the full log output:

<details>

```
^C2019-01-24T16:33:08.726260Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "telemetry", "interval": "8h"}
2019-01-24T16:33:08.726702Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "task"}
2019-01-24T16:33:08.726803Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "http"}
2019-01-24T16:33:08.727037Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "scraper"}
2019-01-24T16:33:08.729274Z	info	Created run; beginning execution	{"log_id": "0DCB8il0000", "svc": "taskd/scheduler", "task_id": "0349ee16153bb000", "run_slot": 0, "run_id": "034c2ca91b545000", "now": 1548208455}
2019-01-24T16:33:08.733496Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca90581c001", "ot_span_id": "034c2ca90581c000", "ot_start": "2019-01-24T16:33:08.630227Z", "ot_stop": "2019-01-24T16:33:08.733466Z", "ot_duration": "103.236ms"}
2019-01-24T16:33:08.738045Z	info	parse	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca91b41c002", "ot_start": "2019-01-24T16:33:08.717606Z", "ot_stop": "2019-01-24T16:33:08.738011Z", "ot_duration": "20.405ms", "ot_child_of": "034c2ca91b41c000"}
2019-01-24T16:33:08.739077Z	info	compile	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca92081c000", "ot_start": "2019-01-24T16:33:08.738349Z", "ot_stop": "2019-01-24T16:33:08.739064Z", "ot_duration": "0.715ms", "ot_child_of": "034c2ca91b41c000"}
2019-01-24T16:33:08.739290Z	info	compiling	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca920c1c001", "ot_start": "2019-01-24T16:33:08.739269Z", "ot_stop": "2019-01-24T16:33:08.739280Z", "ot_duration": "0.011ms", "ot_child_of": "034c2ca920c1c000"}
2019-01-24T16:33:08.739839Z	info	planning	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca920c1c002", "ot_start": "2019-01-24T16:33:08.739675Z", "ot_stop": "2019-01-24T16:33:08.739826Z", "ot_duration": "0.150ms", "ot_child_of": "034c2ca920c1c000"}
2019-01-24T16:33:08.740059Z	info	Executing task (start)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349eab2c011b000", "run_id": "034c2ca913545000", "trace_id": "0DCBA_X0000", "op_name": "execute", "op_event": "start"}
2019-01-24T16:33:08.740149Z	info	queueing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca920c1c003", "ot_start": "2019-01-24T16:33:08.739950Z", "ot_stop": "2019-01-24T16:33:08.740136Z", "ot_duration": "0.186ms", "ot_child_of": "034c2ca920c1c000"}
2019-01-24T16:33:08.740686Z	info	Execution failed to get result	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349eab2c011b000", "run_id": "034c2ca913545000", "trace_id": "0DCBA_X0000", "op_name": "execute", "error": "run canceled"}
2019-01-24T16:33:08.741287Z	info	Executing task (end)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349eab2c011b000", "run_id": "034c2ca913545000", "trace_id": "0DCBA_X0000", "op_name": "execute", "op_event": "end", "op_elapsed": "1.238ms"}
2019-01-24T16:33:08.740984Z	info	executing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca92101c000", "ot_start": "2019-01-24T16:33:08.740613Z", "ot_stop": "2019-01-24T16:33:08.740871Z", "ot_duration": "0.258ms", "ot_child_of": "034c2ca920c1c000"}
2019-01-24T16:33:08.741378Z	info	index_cursor.create	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca92141c000", "ot_start": "2019-01-24T16:33:08.741350Z", "ot_stop": "2019-01-24T16:33:08.741366Z", "ot_duration": "0.015ms", "ot_child_of": "034c2ca92101c000"}
==================
WARNING: DATA RACE
Write at 0x00c0010d2120 by goroutine 81:
  github.com/influxdata/flux/control.(*Query).transitionTo()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:606 +0x159
  github.com/influxdata/flux/control.(*Query).Cancel()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:518 +0x118
  github.com/influxdata/influxdb/task/backend/executor.(*asyncRunPromise).followQuery()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/executor/executor.go:286 +0x524

Previous read at 0x00c0010d2120 by goroutine 83:
  github.com/influxdata/flux/control.(*Controller).processQuery()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:424 +0x29e
  github.com/influxdata/flux/control.(*Controller).run()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:344 +0x3e9

Goroutine 81 (running) created at:
  github.com/influxdata/influxdb/task/backend/executor.newAsyncRunPromise()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/executor/executor.go:252 +0x580
  github.com/influxdata/influxdb/task/backend/executor.(*asyncQueryServiceExecutor).Execute()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/executor/executor.go:215 +0x360
  github.com/influxdata/influxdb/task/backend.(*runner).executeAndWait()
      /Users/mr/go/src/github.com/influxdata/influxdb/task/backend/scheduler.go:636 +0x1b7

Goroutine 83 (running) created at:
  github.com/influxdata/flux/control.New()
      /Users/mr/go/pkg/mod/github.com/influxdata/flux@v0.17.0/control/controller.go:106 +0x624
  github.com/influxdata/influxdb/cmd/influxd/launcher.(*Launcher).run()
      /Users/mr/go/src/github.com/influxdata/influxdb/query/control/controller.go:25 +0x2d08
  github.com/influxdata/influxdb/cmd/influxd/launcher.(*Launcher).Run.func1()
      /Users/mr/go/src/github.com/influxdata/influxdb/cmd/influxd/launcher/launcher.go:179 +0x53
  github.com/influxdata/influxdb/kit/cli.NewCommand.func1()
      /Users/mr/go/src/github.com/influxdata/influxdb/kit/cli/viper.go:51 +0x55
  github.com/spf13/cobra.(*Command).execute()
      /Users/mr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x527
  github.com/spf13/cobra.(*Command).ExecuteC()
      /Users/mr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x3ed
  github.com/influxdata/influxdb/cmd/influxd/launcher.(*Launcher).Run()
      /Users/mr/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0xb0b
  main.main()
      /Users/mr/go/src/github.com/influxdata/influxdb/cmd/influxd/main.go:32 +0x58d
==================
2019-01-24T16:33:08.742366Z	info	all	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca920c1c000", "ot_start": "2019-01-24T16:33:08.739237Z", "ot_stop": "2019-01-24T16:33:08.742342Z", "ot_duration": "3.105ms", "ot_child_of": "034c2ca91b41c000"}
2019-01-24T16:33:08.749550Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca90ec1c001", "ot_span_id": "034c2ca90ec1c000", "ot_start": "2019-01-24T16:33:08.667214Z", "ot_stop": "2019-01-24T16:33:08.749536Z", "ot_duration": "82.319ms"}
2019-01-24T16:33:08.751043Z	info	parse	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca91e41c002", "ot_start": "2019-01-24T16:33:08.729665Z", "ot_stop": "2019-01-24T16:33:08.751027Z", "ot_duration": "21.361ms", "ot_child_of": "034c2ca91e41c000"}
2019-01-24T16:33:08.751378Z	info	compile	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca923c1c000", "ot_start": "2019-01-24T16:33:08.751179Z", "ot_stop": "2019-01-24T16:33:08.751366Z", "ot_duration": "0.187ms", "ot_child_of": "034c2ca91e41c000"}
2019-01-24T16:33:08.751790Z	info	compiling	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca923c1c002", "ot_start": "2019-01-24T16:33:08.751766Z", "ot_stop": "2019-01-24T16:33:08.751778Z", "ot_duration": "0.012ms", "ot_child_of": "034c2ca923c1c001"}
2019-01-24T16:33:08.752080Z	info	planning	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca923c1c003", "ot_start": "2019-01-24T16:33:08.751922Z", "ot_stop": "2019-01-24T16:33:08.752068Z", "ot_duration": "0.146ms", "ot_child_of": "034c2ca923c1c001"}
2019-01-24T16:33:08.752326Z	info	Executing task (start)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca91b545000", "trace_id": "0DCBA__0000", "op_name": "execute", "op_event": "start"}
2019-01-24T16:33:08.752316Z	info	queueing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca92401c000", "ot_start": "2019-01-24T16:33:08.752206Z", "ot_stop": "2019-01-24T16:33:08.752298Z", "ot_duration": "0.092ms", "ot_child_of": "034c2ca923c1c001"}
2019-01-24T16:33:08.752593Z	info	Execution failed to get result	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca91b545000", "trace_id": "0DCBA__0000", "op_name": "execute", "error": "run canceled"}
2019-01-24T16:33:08.752686Z	info	Executing task (end)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca91b545000", "trace_id": "0DCBA__0000", "op_name": "execute", "op_event": "end", "op_elapsed": "0.373ms"}
2019-01-24T16:33:08.752642Z	info	executing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca92401c001", "ot_start": "2019-01-24T16:33:08.752503Z", "ot_stop": "2019-01-24T16:33:08.752614Z", "ot_duration": "0.111ms", "ot_child_of": "034c2ca923c1c001"}
2019-01-24T16:33:08.752972Z	info	index_cursor.create	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca92401c002", "ot_start": "2019-01-24T16:33:08.752943Z", "ot_stop": "2019-01-24T16:33:08.752957Z", "ot_duration": "0.014ms", "ot_child_of": "034c2ca92401c001"}
2019-01-24T16:33:08.774515Z	info	all	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca923c1c001", "ot_start": "2019-01-24T16:33:08.751733Z", "ot_stop": "2019-01-24T16:33:08.774489Z", "ot_duration": "22.755ms", "ot_child_of": "034c2ca91e41c000"}
2019-01-24T16:33:08.780827Z	info	Created run; beginning execution	{"log_id": "0DCB8il0000", "svc": "taskd/scheduler", "task_id": "0349eab2c011b000", "run_slot": 0, "run_id": "034c2ca928545000", "now": 1548204825}
2019-01-24T16:33:08.797191Z	info	Created run; beginning execution	{"log_id": "0DCB8il0000", "svc": "taskd/scheduler", "task_id": "0349ee16153bb000", "run_slot": 0, "run_id": "034c2ca92c145000", "now": 1548208470}
2019-01-24T16:33:08.800422Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91b41c001", "ot_span_id": "034c2ca91b41c000", "ot_start": "2019-01-24T16:33:08.717533Z", "ot_stop": "2019-01-24T16:33:08.800408Z", "ot_duration": "82.873ms"}
2019-01-24T16:33:08.801058Z	info	parse	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca92b41c002", "ot_start": "2019-01-24T16:33:08.781144Z", "ot_stop": "2019-01-24T16:33:08.801045Z", "ot_duration": "19.900ms", "ot_child_of": "034c2ca92b41c000"}
2019-01-24T16:33:08.801534Z	info	compile	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca93041c000", "ot_start": "2019-01-24T16:33:08.801187Z", "ot_stop": "2019-01-24T16:33:08.801526Z", "ot_duration": "0.339ms", "ot_child_of": "034c2ca92b41c000"}
2019-01-24T16:33:08.801707Z	info	compiling	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca93041c002", "ot_start": "2019-01-24T16:33:08.801686Z", "ot_stop": "2019-01-24T16:33:08.801697Z", "ot_duration": "0.011ms", "ot_child_of": "034c2ca93041c001"}
2019-01-24T16:33:08.801951Z	info	planning	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca93041c003", "ot_start": "2019-01-24T16:33:08.801804Z", "ot_stop": "2019-01-24T16:33:08.801944Z", "ot_duration": "0.140ms", "ot_child_of": "034c2ca93041c001"}
2019-01-24T16:33:08.802165Z	info	Executing task (start)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349eab2c011b000", "run_id": "034c2ca928545000", "trace_id": "0DCBA_lW000", "op_name": "execute", "op_event": "start"}
2019-01-24T16:33:08.802148Z	info	queueing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca93081c000", "ot_start": "2019-01-24T16:33:08.802045Z", "ot_stop": "2019-01-24T16:33:08.802135Z", "ot_duration": "0.089ms", "ot_child_of": "034c2ca93041c001"}
2019-01-24T16:33:08.802415Z	info	Execution failed to get result	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349eab2c011b000", "run_id": "034c2ca928545000", "trace_id": "0DCBA_lW000", "op_name": "execute", "error": "run canceled"}
2019-01-24T16:33:08.802552Z	info	executing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca93081c001", "ot_start": "2019-01-24T16:33:08.802270Z", "ot_stop": "2019-01-24T16:33:08.802525Z", "ot_duration": "0.255ms", "ot_child_of": "034c2ca93041c001"}
2019-01-24T16:33:08.802672Z	info	Executing task (end)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349eab2c011b000", "run_id": "034c2ca928545000", "trace_id": "0DCBA_lW000", "op_name": "execute", "op_event": "end", "op_elapsed": "0.519ms"}
2019-01-24T16:33:08.802891Z	info	all	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca93041c001", "ot_start": "2019-01-24T16:33:08.801653Z", "ot_stop": "2019-01-24T16:33:08.802878Z", "ot_duration": "1.225ms", "ot_child_of": "034c2ca92b41c000"}
2019-01-24T16:33:08.803027Z	info	index_cursor.create	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca930c1c000", "ot_start": "2019-01-24T16:33:08.802969Z", "ot_stop": "2019-01-24T16:33:08.803016Z", "ot_duration": "0.017ms", "ot_child_of": "034c2ca93081c001"}
2019-01-24T16:33:08.811494Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca91e41c001", "ot_span_id": "034c2ca91e41c000", "ot_start": "2019-01-24T16:33:08.729589Z", "ot_stop": "2019-01-24T16:33:08.811481Z", "ot_duration": "81.890ms"}
2019-01-24T16:33:08.812013Z	info	parse	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca92f41c002", "ot_start": "2019-01-24T16:33:08.797677Z", "ot_stop": "2019-01-24T16:33:08.812001Z", "ot_duration": "14.324ms", "ot_child_of": "034c2ca92f41c000"}
2019-01-24T16:33:08.812388Z	info	compile	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca93301c000", "ot_start": "2019-01-24T16:33:08.812164Z", "ot_stop": "2019-01-24T16:33:08.812380Z", "ot_duration": "0.217ms", "ot_child_of": "034c2ca92f41c000"}
2019-01-24T16:33:08.812559Z	info	compiling	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca93301c002", "ot_start": "2019-01-24T16:33:08.812536Z", "ot_stop": "2019-01-24T16:33:08.812548Z", "ot_duration": "0.012ms", "ot_child_of": "034c2ca93301c001"}
2019-01-24T16:33:08.812797Z	info	planning	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca93301c003", "ot_start": "2019-01-24T16:33:08.812652Z", "ot_stop": "2019-01-24T16:33:08.812787Z", "ot_duration": "0.135ms", "ot_child_of": "034c2ca93301c001"}
2019-01-24T16:33:08.813020Z	info	Executing task (start)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca92c145000", "trace_id": "0DCBA_o0000", "op_name": "execute", "op_event": "start"}
2019-01-24T16:33:08.813042Z	info	queueing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca93301c004", "ot_start": "2019-01-24T16:33:08.812909Z", "ot_stop": "2019-01-24T16:33:08.813026Z", "ot_duration": "0.117ms", "ot_child_of": "034c2ca93301c001"}
2019-01-24T16:33:08.813269Z	info	Execution failed to get result	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca92c145000", "trace_id": "0DCBA_o0000", "op_name": "execute", "error": "run canceled"}
2019-01-24T16:33:08.813364Z	info	Executing task (end)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca92c145000", "trace_id": "0DCBA_o0000", "op_name": "execute", "op_event": "end", "op_elapsed": "0.359ms"}
2019-01-24T16:33:08.813324Z	info	executing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca93341c000", "ot_start": "2019-01-24T16:33:08.813186Z", "ot_stop": "2019-01-24T16:33:08.813299Z", "ot_duration": "0.113ms", "ot_child_of": "034c2ca93301c001"}
2019-01-24T16:33:08.813666Z	info	all	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca93301c001", "ot_start": "2019-01-24T16:33:08.812505Z", "ot_stop": "2019-01-24T16:33:08.813651Z", "ot_duration": "1.146ms", "ot_child_of": "034c2ca92f41c000"}
2019-01-24T16:33:08.813720Z	info	index_cursor.create	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca93341c001", "ot_start": "2019-01-24T16:33:08.813692Z", "ot_stop": "2019-01-24T16:33:08.813705Z", "ot_duration": "0.013ms", "ot_child_of": "034c2ca93341c000"}
2019-01-24T16:33:08.839136Z	info	Created run; beginning execution	{"log_id": "0DCB8il0000", "svc": "taskd/scheduler", "task_id": "0349eab2c011b000", "run_slot": 0, "run_id": "034c2ca937145000", "now": 1548204830}
2019-01-24T16:33:08.850923Z	info	Created run; beginning execution	{"log_id": "0DCB8il0000", "svc": "taskd/scheduler", "task_id": "0349ee16153bb000", "run_slot": 0, "run_id": "034c2ca93a945000", "now": 1548208485}
2019-01-24T16:33:08.857665Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92b41c001", "ot_span_id": "034c2ca92b41c000", "ot_start": "2019-01-24T16:33:08.781078Z", "ot_stop": "2019-01-24T16:33:08.857651Z", "ot_duration": "76.571ms"}
2019-01-24T16:33:08.868906Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca92f41c001", "ot_span_id": "034c2ca92f41c000", "ot_start": "2019-01-24T16:33:08.797579Z", "ot_stop": "2019-01-24T16:33:08.868892Z", "ot_duration": "71.311ms"}
2019-01-24T16:33:08.870330Z	info	parse	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca939c1c001", "ot_span_id": "034c2ca93a01c000", "ot_start": "2019-01-24T16:33:08.840261Z", "ot_stop": "2019-01-24T16:33:08.870319Z", "ot_duration": "30.057ms", "ot_child_of": "034c2ca939c1c000"}
2019-01-24T16:33:08.870746Z	info	compile	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca939c1c001", "ot_span_id": "034c2ca94181c000", "ot_start": "2019-01-24T16:33:08.870435Z", "ot_stop": "2019-01-24T16:33:08.870738Z", "ot_duration": "0.303ms", "ot_child_of": "034c2ca939c1c000"}
2019-01-24T16:33:08.870931Z	info	compiling	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca939c1c001", "ot_span_id": "034c2ca94181c002", "ot_start": "2019-01-24T16:33:08.870906Z", "ot_stop": "2019-01-24T16:33:08.870920Z", "ot_duration": "0.014ms", "ot_child_of": "034c2ca94181c001"}
2019-01-24T16:33:08.871205Z	info	planning	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca939c1c001", "ot_span_id": "034c2ca941c1c000", "ot_start": "2019-01-24T16:33:08.871058Z", "ot_stop": "2019-01-24T16:33:08.871198Z", "ot_duration": "0.140ms", "ot_child_of": "034c2ca94181c001"}
2019-01-24T16:33:08.871374Z	info	queueing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca939c1c001", "ot_span_id": "034c2ca941c1c001", "ot_start": "2019-01-24T16:33:08.871299Z", "ot_stop": "2019-01-24T16:33:08.871363Z", "ot_duration": "0.064ms", "ot_child_of": "034c2ca94181c001"}
2019-01-24T16:33:08.871496Z	info	all	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca939c1c001", "ot_span_id": "034c2ca94181c001", "ot_start": "2019-01-24T16:33:08.870874Z", "ot_stop": "2019-01-24T16:33:08.871481Z", "ot_duration": "0.606ms", "ot_child_of": "034c2ca939c1c000"}
2019-01-24T16:33:08.874762Z	info	parse	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca93cc1c002", "ot_start": "2019-01-24T16:33:08.851777Z", "ot_stop": "2019-01-24T16:33:08.874751Z", "ot_duration": "22.973ms", "ot_child_of": "034c2ca93cc1c000"}
2019-01-24T16:33:08.875060Z	info	compile	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca94281c000", "ot_start": "2019-01-24T16:33:08.874868Z", "ot_stop": "2019-01-24T16:33:08.875050Z", "ot_duration": "0.182ms", "ot_child_of": "034c2ca93cc1c000"}
2019-01-24T16:33:08.875243Z	info	compiling	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca942c1c001", "ot_start": "2019-01-24T16:33:08.875220Z", "ot_stop": "2019-01-24T16:33:08.875232Z", "ot_duration": "0.012ms", "ot_child_of": "034c2ca942c1c000"}
2019-01-24T16:33:08.875469Z	info	planning	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca942c1c002", "ot_start": "2019-01-24T16:33:08.875333Z", "ot_stop": "2019-01-24T16:33:08.875461Z", "ot_duration": "0.128ms", "ot_child_of": "034c2ca942c1c000"}
2019-01-24T16:33:08.875677Z	info	Executing task (start)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca93a945000", "trace_id": "0DCBAa2l000", "op_name": "execute", "op_event": "start"}
2019-01-24T16:33:08.875749Z	info	queueing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca942c1c003", "ot_start": "2019-01-24T16:33:08.875561Z", "ot_stop": "2019-01-24T16:33:08.875734Z", "ot_duration": "0.173ms", "ot_child_of": "034c2ca942c1c000"}
2019-01-24T16:33:08.875871Z	info	Execution failed to get result	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca93a945000", "trace_id": "0DCBAa2l000", "op_name": "execute", "error": "run canceled"}
2019-01-24T16:33:08.875965Z	info	Executing task (end)	{"log_id": "0DCB8il0000", "service": "task-executor", "task_id": "0349ee16153bb000", "run_id": "034c2ca93a945000", "trace_id": "0DCBAa2l000", "op_name": "execute", "op_event": "end", "op_elapsed": "0.315ms"}
2019-01-24T16:33:08.876123Z	info	executing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca94301c000", "ot_start": "2019-01-24T16:33:08.875894Z", "ot_stop": "2019-01-24T16:33:08.876095Z", "ot_duration": "0.201ms", "ot_child_of": "034c2ca942c1c000"}
2019-01-24T16:33:08.876466Z	info	all	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca942c1c000", "ot_start": "2019-01-24T16:33:08.875190Z", "ot_stop": "2019-01-24T16:33:08.876412Z", "ot_duration": "1.222ms", "ot_child_of": "034c2ca93cc1c000"}
2019-01-24T16:33:08.876669Z	info	index_cursor.create	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca94301c001", "ot_start": "2019-01-24T16:33:08.876641Z", "ot_stop": "2019-01-24T16:33:08.876654Z", "ot_duration": "0.013ms", "ot_child_of": "034c2ca94301c000"}
2019-01-24T16:33:08.884026Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca939c1c001", "ot_span_id": "034c2ca939c1c000", "ot_start": "2019-01-24T16:33:08.839393Z", "ot_stop": "2019-01-24T16:33:08.884009Z", "ot_duration": "44.615ms"}
2019-01-24T16:33:08.907497Z	info	Created run; beginning execution	{"log_id": "0DCB8il0000", "svc": "taskd/scheduler", "task_id": "0349ee16153bb000", "run_slot": 0, "run_id": "034c2ca949145000", "now": 1548208500}
2019-01-24T16:33:08.919418Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca93cc1c001", "ot_span_id": "034c2ca93cc1c000", "ot_start": "2019-01-24T16:33:08.851616Z", "ot_stop": "2019-01-24T16:33:08.919405Z", "ot_duration": "67.787ms"}
2019-01-24T16:33:08.921906Z	info	parse	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca94ac1c001", "ot_span_id": "034c2ca94ac1c002", "ot_start": "2019-01-24T16:33:08.907877Z", "ot_stop": "2019-01-24T16:33:08.921889Z", "ot_duration": "14.011ms", "ot_child_of": "034c2ca94ac1c000"}
2019-01-24T16:33:08.922180Z	info	compile	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca94ac1c001", "ot_span_id": "034c2ca94e81c000", "ot_start": "2019-01-24T16:33:08.922012Z", "ot_stop": "2019-01-24T16:33:08.922172Z", "ot_duration": "0.160ms", "ot_child_of": "034c2ca94ac1c000"}
2019-01-24T16:33:08.922344Z	info	compiling	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca94ac1c001", "ot_span_id": "034c2ca94e81c002", "ot_start": "2019-01-24T16:33:08.922325Z", "ot_stop": "2019-01-24T16:33:08.922337Z", "ot_duration": "0.012ms", "ot_child_of": "034c2ca94e81c001"}
2019-01-24T16:33:08.922566Z	info	planning	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca94ac1c001", "ot_span_id": "034c2ca94e81c003", "ot_start": "2019-01-24T16:33:08.922439Z", "ot_stop": "2019-01-24T16:33:08.922559Z", "ot_duration": "0.120ms", "ot_child_of": "034c2ca94e81c001"}
2019-01-24T16:33:08.922725Z	info	queueing	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca94ac1c001", "ot_span_id": "034c2ca94e81c004", "ot_start": "2019-01-24T16:33:08.922661Z", "ot_stop": "2019-01-24T16:33:08.922716Z", "ot_duration": "0.054ms", "ot_child_of": "034c2ca94e81c001"}
2019-01-24T16:33:08.922811Z	info	all	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca94ac1c001", "ot_span_id": "034c2ca94e81c001", "ot_start": "2019-01-24T16:33:08.922295Z", "ot_stop": "2019-01-24T16:33:08.922801Z", "ot_duration": "0.505ms", "ot_child_of": "034c2ca94ac1c000"}
2019-01-24T16:33:08.933289Z	info	task.run.execution	{"log_id": "0DCB8il0000", "ot_trace_id": "034c2ca94ac1c001", "ot_span_id": "034c2ca94ac1c000", "ot_start": "2019-01-24T16:33:08.907795Z", "ot_stop": "2019-01-24T16:33:08.933278Z", "ot_duration": "25.482ms"}
2019-01-24T16:33:08.933484Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "nats"}
2019-01-24T16:33:08.937684Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "bolt"}
2019-01-24T16:33:08.938250Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "query"}
2019-01-24T16:33:08.938358Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "storage-engine"}
2019-01-24T16:33:08.938443Z	info	Stopping	{"log_id": "0DCB8il0000", "service": "storage-engine", "component": "retention_enforcer", "check_interval": "1h"}
```

</details>

It appears to be `q.currentCtx` reassigned in one goroutine and read in another:

https://github.com/influxdata/flux/blob/3369fa554564cb543a511d27e4371b43f8666d17/control/controller.go#L424
https://github.com/influxdata/flux/blob/3369fa554564cb543a511d27e4371b43f8666d17/control/controller.go#L606

### PR DESCRIPTION
**Pull request by jsternberg**
- [x] docs/SPEC.md updated
- [x] Test cases written

This refactors the controller query and how the controller interacts
with that query. Previously, the query had an ill-defined lifecycle and
it could be arbitrarily canceled at any time that caused race conditions
when transitioning between states. The transition touched values that
were not protected by a mutex which caused a data race.

The query has now been changed so the `Cancel()` method only _signals_
that the query should be canceled and does that by using the query
context and sending that downstream. This causes the state to transition
lazily so when the query attempts to transition to a different state,
it will automatically transition to the canceled state and report that
it failed to transition to a new state. When the query controller
attempts to report an error, it realizes that the query has been
canceled and uses the error on the query context instead.

In addition, to ensure that the controller reports the correct state of
a query to a task manager, the `State()` method has been modified to check
the context to see if the query has been canceled even if the stateh
hasn't been updated.

With these changes, it means that all state transitions and changes
to sensitive state happen within the controller execution loop instead
of potentially running outside of it.

The channel returned by `Ready()` will only be set when an error is
caught during the execution lifecycle (such as by cancellation) or when
the query has successfully executed. This makes the state machine much
more simple than previously.

Fixes #928.

### CODE REVIEW

File: control/controller.go [hunk 1]
```diff
@@ -346,7 +345,7 @@ func (c *Controller) run() {
 				pq.Pop()
 			}
 			if err != nil {
-				go q.setErr(err)
+				q.setErr(err)
```
Comment (docmerlin) [inline control/controller.go]: Good, that groutine was completely unnecessary.
