### PR TITLE
fix(join): return error if user modifies group key

### LINKED ISSUE #4909: Join package: report error if user attempts to modify the group key
Right now, users can define `as` functions that drop group key columns in the output records. The output tables still retain the same grouping, but the missing columns will cause problems elsewhere in the product. The join transformation should protect against this by throwing an error if the `as` function returns a record that omits any group key columns.

### PR DESCRIPTION
**Pull request by scbrickley**
Return an error if a user defines an `as` function that returns a record that is missing a group key column.

Fixes #4909

### CODE REVIEW

File: stdlib/join/join_fn.go [hunk 1]
```diff
@@ -211,6 +211,22 @@ func (f *JoinFn) createSchema(record values.Object) ([]flux.ColMeta, error) {
 			Type:  ty,
 		})
 	}
+	for _, gcol := range groupkey.Cols() {
+		found := false
+		for _, col := range cols {
+			if gcol == col {
+				found = true
```
Comment (OfTheDelmer) [inline stdlib/join/join_fn.go:218]: We could `break` after here. Although, if cols is sorted would a quick binary search be worthwhile?

**Review by OfTheDelmer — APPROVED** [review]
