### PR TITLE
fix(ast): format AST preserving operator precedence

### LINKED ISSUE #1012: Formatting AST loses parentheses and thus operator associativity
An AST that was parsed from `(1.0 * 2.0 + 4.0 / 6.0 - 10.0) * r._value` gets formatted out by `ast.Format()` as `1.0 * 2.0 + 4.0 / 6.0 - 10.0 * r._value`, losing parentheses and thus losing the original associativity.

Either parentheses should be explicitly preserved in the AST or the Formatter needs to add them back according to operator precedence, when needed.

### PR DESCRIPTION
**Pull request by affo**
Closes #1012 

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

### CODE REVIEW

File: ast/format.go [hunk 1]
```diff
@@ -64,6 +61,113 @@ func (f *formatter) writeComment(comment string) {
...
+	getIntForOp(NotEmptyOperator):         4,
+	getIntForOp(EmptyOperator):            4,
+	getIntForOp(EqualOperator):            4,
+	getIntForOp(NotEqualOperator):         4,
+	getIntForOp(RegexpMatchOperator):      4,
+	getIntForOp(NotRegexpMatchOperator):   4,
+	getIntForOp(NotOperator):              5,
+	// theses are LogicalOperatorKinds:
+	getIntForLOp(AndOperator): 6,
+	getIntForLOp(OrOperator):  7,
```
Comment (affo) [inline ast/format.go]: Here I changed the precedence of `and` wrt `or` according to https://github.com/influxdata/flux/issues/1077.
If we do not agree on that, I can change to `6, 6` and avoid skipping related tests.

File: ast/format.go [hunk 2]
```diff
@@ -73,7 +177,9 @@ func (f *formatter) formatPackage(n *Package) {
 			f.writeRune('\n')
 			f.writeRune('\n')
 		}
-		f.writeComment(file.Name)
+		if len(file.Name) > 0 {
+			f.writeComment(file.Name)
+		}
```
Comment (affo) [inline ast/format.go]: This fixes the issue we had when formatting a generated AST that doesn't have a file provenance.
Otherwise, it would generate:

```
package main
//

...
```

The related test is below

File: ast/format_test.go [hunk 3]
```diff
@@ -283,27 +320,79 @@ highestAverage = (n, columns=["_value"], by, tables=<-) =>
...
+			name:   "unary with pars",
+			script: `not (b and c)`,
+		},
+		{
+			name:   "function call with pars",
+			script: `(a + b * c == 0)(foo: "bar")`,
+		},
+		{
+			name:   "member with pars",
+			script: `((a + b) * c)._value`,
```
Comment (jlapacik) [inline ast/format_test.go]: Should this be a test case? I guess this parses just fine, but I don't think it would type check. Are there any member expression examples that are valid Flux expressions? I can't really think of any.

File: ast/format_test.go [hunk 4]
```diff
@@ -283,27 +320,79 @@ highestAverage = (n, columns=["_value"], by, tables=<-) =>
...
+		},
+		{
+			name:   "index with pars",
+			script: `((a - b) / (c + d))[3]`,
```
Comment (jlapacik) [inline ast/format_test.go]: Same here. This parses just fine, but it's not a valid Flux expression (would not pass type checking). Is it possible to come up with a test case for index expressions that is also a valid Flux expression?

File: ast/format.go [hunk 5]
```diff
@@ -64,6 +61,113 @@ func (f *formatter) writeComment(comment string) {
...
+
+func getPrecedenceForLOp(op LogicalOperatorKind) int {
+	return getPrecedence(getIntForLOp(op))
+}
+
+// this matches the SPEC
+var opPrecedence = map[int]int{
+	functionCall: 1,
+	member:       1,
+	index:        1,
```
Comment (jlapacik) [inline ast/format.go]: Do index and member need to be included? See my comments regarding their associated test cases.

Comment (affo) [reply ast/format.go]: I absolutely see your point, but I made it for completeness and in order to directly match the SPEC. I also know that those in the tests wouldn't pass type checking, but in the future they could be (say we support `+` for arrays). So I wanted to check if operator precedence was respected even in that cases, also given that there is actually a formally defined precedence of (say) member VS addition in the SPEC.

File: ast/format_test.go (hunk 4 above)
Comment (affo) [reply ast/format_test.go]: Yeah, tests for index and member expressions are in `TestFormat_Nodes`. This test is specific about associativity/precedence. The rest of the answer is below.

File: ast/format_test.go (hunk 3 above)
Comment (affo) [reply ast/format_test.go]: Answered below.

File: ast/format.go [hunk 6]
```diff
@@ -64,6 +61,113 @@ func (f *formatter) writeComment(comment string) {
...
+	getIntForOp(NotEqualOperator):         4,
+	getIntForOp(RegexpMatchOperator):      4,
+	getIntForOp(NotRegexpMatchOperator):   4,
+	getIntForOp(NotOperator):              5,
+	// theses are LogicalOperatorKinds:
+	getIntForLOp(AndOperator): 6,
+	getIntForLOp(OrOperator):  7,
+}
+
+func (f *formatter) formatChildWithPars(parent, child Node) {
```
[the remark this answers is not in the document]
Comment (affo) [reply ast/format.go]: 👍

File: ast/format.go [hunk 7]
```diff
@@ -253,27 +359,29 @@ func (f *formatter) formatFunctionExpression(n *FunctionExpression) {
...
-	f.writeString(n.Operator.String())
-	f.writeRune(' ')
-	f.formatNode(n.Right)
+	f.formatBinary(n.Operator.String(), n, n.Left, n.Right)
 }
 
 func (f *formatter) formatLogicalExpression(n *LogicalExpression) {
-	f.formatNode(n.Left)
+	f.formatBinary(n.Operator.String(), n, n.Left, n.Right)
+
```
[the remark this answers is not in the document]
Comment (affo) [reply ast/format.go]: 👍

**Comment by affo** [comment]
In general, I think this PR should be merged after I produce a fix for https://github.com/influxdata/flux/issues/1077 (thanks to @jsternberg 😄  ).
In that case, I could remove skipping tests. I will ping you @jlapacik once it is done

**Comment by affo** [comment]
I rebase on the branch of #1098 .

@jlapacik In the last commit I addressed your comments and removed the skipped tests for bad parenthesis.

File: ast/format_test.go [hunk 8]
```diff
@@ -10,12 +10,9 @@ import (
...
 var skip = map[string]string{
-	"array_expr":            "without pars -> bad syntax, with pars formatting removes them",
-	"conditional":           "how is a conditional expression defined in spec?",
-	"multi_var_decl":        "how is a variable declaration with multiple declarations represented?",
-	"logic":                 "the AST created for logic ops is wrong (https://github.com/influxdata/flux/issues/1077)",
-	"logic with comparison": "the AST created for logic ops is wrong (https://github.com/influxdata/flux/issues/1077)",
-	"logic and math":        "the AST created for logic ops is wrong (https://github.com/influxdata/flux/issues/1077)",
+	"array_expr":     "without pars -> bad syntax, with pars formatting removes them",
+	"conditional":    "how is a conditional expression defined in spec?",
+	"multi_var_decl": "how is a variable declaration with multiple declarations represented?",
```
Comment (jlapacik) [inline ast/format_test.go]: Flux doesn't have a `var` keyword. Can you remove this test?

Comment (affo) [reply ast/format_test.go]: absolutely, we had it in the past 😅
