### PR TITLE
fix(repl): clear return for each repl command

### LINKED ISSUE #833: REPL displays previous result for import statements
Sets to reproduce:

```
> import "csv"
> csv
pkg{from}
> import "http"
pkg{from}
> http
pkg{to}
```

My guess is that the return value on the scope is not getting cleared so its being printed again.

### PR DESCRIPTION
**Pull request by nathanielc**
Fixes #833

### Done checklist
- [ ] docs/SPEC.md updated
- [ ] Test cases written

### CODE REVIEW

File: repl/repl.go [hunk 1]
```diff
@@ -153,6 +153,8 @@ func (r *REPL) executeLine(t string) (values.Value, error) {
 		return nil, err
 	}
 
+	r.scope.SetReturn(nil)
```
Comment (jlapacik) [inline repl/repl.go]: Correct me if I'm wrong, but is this necessary? Why not just use the value returned by `interpreter.Eval` and not mess with the scope? `interpreter.Eval` will return any produced side effects. This means TableObjects as well as any value resulting from any expression statements.

Comment (nathanielc) [reply repl/repl.go]: I had a similar thought, but their could be many returned side effects and there is no consistent way to know which side effect is the result of the expression. So for now I just made the change I knew would fix the issue. 

I'll create a new issue to address using side effects instead of the scope return value for the REPL.

Comment (jlapacik) [reply repl/repl.go]: Ok sounds good to me.

Comment (nathanielc) [reply repl/repl.go]: https://github.com/influxdata/flux/issues/867
