### PR TITLE
fix: logical null handling

### LINKED ISSUE #5188: Realign logical and/or with spec regarding nulls
In the Flux spec, we detail how nulls should be treated when used in logical operators (`and`, `or`).

https://github.com/influxdata/flux/blob/edc16bf677327e55050d59e781b2657273c4f397/docs/SPEC.md?plain=1#L1439-L1444

Today we have two implementations for logical ops, the regular and the vectorized. Neither of these implementations match the spec completely when it comes to null handling. The vectorized implementation also has some correctness problems re: nulls.

For the vectorized implementation, note that nulls come in **2 flavors**:
- **individual nulls** within a vector input (ex: when `r.field` is sometimes null, sometimes not)
- **"constant" nulls** when the vector is missing (ex: when `r.field` where `r.field` just doesn't exist)

Work done in https://github.com/influxdata/flux/pull/5181 updated the vectorized code path such that it converts the latter to be a "constant false" which is not correct per the spec, but avoids a runtime error, while also weakly helping to mitigate a correctness problem in `vectorOr`.

> Vectorized conditionals ran into similar issues re: nulls. The fix for conditionals happened here: https://github.com/influxdata/flux/pull/5118 and the noteworthy bit is how the fix involved updating the constant-handling code to take pointers to scalar values so they could handle the "constant null" case. Something similar may need to happen for logical ops in order to adhere to the spec 100%.

See the comments in #5181 for more discussion on the defects found today.

DOD:
- write acceptance tests that demonstrate the table listing in the spec for:
  - vectorized (assert that the vectorized map planner rule is used)
  - non-vectorized (assert the vectorized planner rule is _not used_, you can include a non-vectorized function call in your map fn to force it to not vectorize...)
    - feature flag this breaking change
    - check both interpreter and compiler logic (i.e. boolean logic inside and outside of map)
  - include tests that demonstrate **both flavors** of nulls for the vectorized path
- update all implementations to match the null handling rules outlined in the spec such that the tests pass

### PR DESCRIPTION
**Pull request by onelson**
Fixes #5188

During an earlier attempt #5181 to fix a type-error problem in the vectorized logical operator implementation, we identified some deviation from the spec in how it worked with respect to `null` inputs. We also found the standard row-based version of logical ops _also deviated_ but in different ways.

This diff attempts to align all logical operator implementations (vectorized, row-based, as well as "in the interpreter") to be representative of what we have in the spec.

In addition to adhering to the spec re: nulls, this diff also adds short-circuiting support to the vectorized implementation in a similar fashion to vectorized conditionals.
This is achieved by checking the left-hand-side vector to see if all the elements are a single value. When this is the case and the value happens to be a short-circuit for the given op, we can skip evaluating the right-hand side entirely.

> In cases where all the elements are the same, but are not useful for short-circuiting, we can still use this information to select a "const" implementation for the op (where one side is fixed throughout), just like in the case of a `VectorRepeatValue`.

## Feature Flagging

Since the null handling aspect changes the behavior of _all logical op_ implementations in flux, the modifications to the conventional row-based and interpreter impls have been guarded with a new feature flag: `strictNullLogicalOps`.

The vectorized impl will use the newly aligned code with or without the `strictNullLogicalOps` flag set.

Since the status quo behavior is not aligned with the spec, we could consider this a "bug fix" but it is a **breaking change** nonetheless. Should there be users who relied on the prior behavior, the flag is our escape hatch to give the affected users a respite to update their scripts if needed.

### Checklist

Dear Author :wave:, the following checks should be completed (or explicitly dismissed) before merging.

- [x] ✏️ Write a PR description, regardless of triviality, to include the _value_ of this PR
- [x] 🔗 Reference related issues
- [x] 🏃 Test cases are included to exercise the new code
- [ ] 🧪 If **new packages** are being introduced to stdlib, link to Working Group discussion notes and ensure it lands under `experimental/`
- [ ] 📖 If **language features** are changing, ensure `docs/Spec.md` has been updated

Dear Reviewer(s) :wave:, you are responsible (among others) for ensuring the completeness and quality of the above before approval.

### CODE REVIEW

**Comment by onelson** [comment]
Initial test run. The tests might still need to be reworked since I'm not 100% sure where I should be expecting untyped null output (ie, missing columns) or typed nulls.

```
go run ./cmd/flux test --test logical_untyped_null_vectorized,logical_typed_null_vectorized,logical_untyped_null,logical_typed_null
xxxx
failures:

        stdlib/universe/map_test.flux: logical_typed_null_vectorized ... fail: Table: keys: []
          _diff:string    _true:bool   _false:bool    _null:bool  nullOrFalse:bool  nullOrTrue:bool  nullOrNull:bool  nullAndFalse:bool  nullAndTrue:bool  nullAndNull:bool  
----------------------  ------------  ------------  ------------  ----------------  ---------------  ---------------  -----------------  ----------------  ----------------  
                     -          true         false                                             true                               false                                      
                     +          true         false                                                                                                                           


        stdlib/universe/map_test.flux: logical_untyped_null_vectorized ... fail: Table: keys: []
          _diff:string    _true:bool   _false:bool  nullOrTrue:bool  nullAndFalse:bool  nullOrNull:bool  nullAndTrue:bool  nullAndNull:bool  nullOrFalse:bool  
----------------------  ------------  ------------  ---------------  -----------------  ---------------  ----------------  ----------------  ----------------  
                     -          true         false             true              false                                                                         
                     +          true         false             true              false            false             false             false             false  


        stdlib/universe/map_test.flux: logical_typed_null ... fail: Table: keys: []
          _diff:string    _true:bool   _false:bool    _null:bool  nullOrFalse:bool  nullOrTrue:bool  nullOrNull:bool  nullAndFalse:bool  nullAndTrue:bool  nullAndNull:bool  
----------------------  ------------  ------------  ------------  ----------------  ---------------  ---------------  -----------------  ----------------  ----------------  
                     -          true         false                                             true                               false                                      
                     +          true         false                           false             true                               false             false             false  


        stdlib/universe/map_test.flux: logical_untyped_null ... fail: Table: keys: []
          _diff:string    _true:bool   _false:bool  nullOrTrue:bool  nullAndFalse:bool  nullAndNull:bool  nullAndTrue:bool  nullOrFalse:bool  nullOrNull:bool  
----------------------  ------------  ------------  ---------------  -----------------  ----------------  ----------------  ----------------  ---------------  
                     -          true         false             true              false                                                                         
                     +          true         false             true              false             false             false             false                   



---
Found 864 tests: passed 0, failed 4, skipped 860
exit status 1
```

**Comment by onelson** [comment]
@scbrickley this is the "likely messy" work I didn't want to dive into in #5181. Assigned you and @nathanielc since y'all both had eyes on the earlier PR (and @wolffcm, auto-assigned, happens to be unavailable).

File: compiler/vectorized_test.go [hunk 1]
```diff
@@ -208,6 +208,89 @@ func TestVectorizedFns(t *testing.T) {
...
 		},
+		{
+			name:         "logical expressions",
+			fn:           "(r) => ({ r with c: r._a and r._b, d: r._a or r._b })",
+			vectorizable: true,
+			skipComp:     true,
+		},
+	}
+
+	logicalTests := []struct {
```
Comment (onelson) [inline compiler/vectorized_test.go:219]: These go-side tests are the only place we verify that values in the vectorized code path are retained/released correctly. It appears we didn't have any for logical ops before now.

It looks like I'm testing for correctness here, but that's the aim. Mostly I'm trying to hit different short-circuit cases to verify memory accounting when (main) early returns are in play.

File: compiler/compiler.go [hunk 2]
```diff
@@ -634,8 +634,11 @@ func compile(n semantic.Node, subst semantic.Substitutor) (Evaluator, error) {
 				right:    r,
 			}, nil
 		}
-
-		return &logicalEvaluator{
+		// TODO(onelson): try to select strict or regular logical here.
+		//   Need ctx to read flagger.
+		//   Currently this happens during Eval() where ctx is available and
+		//   will fallback to the regular logicalEvaluator if the flag is unset.
+		return &logicalStrictNullEvaluator{
```
Comment (onelson) [inline compiler/compiler.go:641]: This would be the ideal spot to branch, but we need the ctx to look at flags. Maybe y'all know how I can get the flagging info here without junking up the existing signatures?

File: array/binary.go [hunk 3]
```diff
@@ -15,42 +15,60 @@ func And(l, r *Boolean, mem memory.Allocator) (*Boolean, error) {
...
 		}
 	}
 	a := b.NewBooleanArray()
 	b.Release()
 	return a, nil
 }
 
-func AndRConst(l *Boolean, r bool, mem memory.Allocator) (*Boolean, error) {
-	n := l.Len()
+func AndConst(fixed *bool, arr *Boolean, mem memory.Allocator) (*Boolean, error) {
```
Comment (onelson) [inline array/binary.go:49]: When I added the initial "vec repeat" support for logical ops I didn't realize the op was commutative. Now that I'm wise to this, I updated this to just swap the args around at the call sites instead of having L and R versions.

File: stdlib/universe/map_test.flux [hunk 4]
```diff
@@ -538,39 +538,206 @@ testcase vectorize_nested_logicals {
...
+                        trueOrNull: r._true or r._null,
+                        nullAndTrue: r._null and r._true,
+                        trueAndNull: r._true and r._null,
+                        nullAndNull: r._null and r._null,
+                        nullOrNull: r._null or r._null,
+                    }),
+            )
+            |> drop(columns: ["_true", "_false"])
+
+    testing.diff(want: want, got: got)
```
Comment (nathanielc) [inline stdlib/universe/map_test.flux:613]: At first I was confused how this test could pass then I realized the missing labels in the want where the values that should be null. Maybe adding a comment to remind the reader that a missing column is an untyped null would help?

**Review by nathanielc — APPROVED** [review]
These tests are great! One small suggestion below.

File: stdlib/universe/map_test.flux (hunk 4 above)
Comment (onelson) [reply stdlib/universe/map_test.flux:616]: Added comments in 61f021a to explain how the untyped nulls are introduced. Yeah - it's a bit of a trick to make this happen on purpose :woozy_face:

**Comment by onelson** [comment]
There'll be some conflicts on this branch until I close or merge the root branch (from the initial PR #5181). I'll clean that up once folks have had their weigh-in on this diff.

**Review by scbrickley — APPROVED** [review]
This looks good to me. I am missing some context because I haven't been super involved with the vec repeat work, but I think I understand what's being implemented here.

Merge away :+1:
