### PR TITLE
Fix/keep

### LINKED ISSUE #330: Call to flux function keep() produces "column doesn't exist" error
This query produces an error:
```
from(bucket:"telegraf")
|> range(start: -1m)
|> keep(columns: ["_measurement"])
```
Error:
```
Error: drop error: column "fstype" doesn't exist
```
I guess that it computes the columns to drop form the first table, and when those columns are not in subsequent tables, it complains?

### PR DESCRIPTION
**Pull request by jlapacik**
Fixes #330 .

### CODE REVIEW

File: functions/transformations/schema_mutators.go [hunk 1]
```diff
@@ -206,20 +206,23 @@ func NewDropKeepMutator(qs flux.OperationSpec) (*DropKeepMutator, error) {
...
+	// then we must be performing the `drop` operation. Note that drop
+	// columns will be present even if we are performing the `keep`
+	// operation. So we must check the keep columns first.
 	if m.KeepCols != nil {
 		for c := range m.KeepCols {
 			if err := checkCol(c, tableCols); err != nil {
 				return errors.Wrap(err, "keep error")
 			}
 		}
+	} else if m.DropCols != nil {
```
Comment (wolffcm) [inline functions/transformations/schema_mutators.go]: Looking at the code that does the mutation here:

https://github.com/influxdata/flux/blob/master/functions/transformations/schema_mutators.go#L267-L271

I think the calls to `checkColumns()` and `keepToDropCols()` should be transposed.

It seems like we are performing the check on the set of `dropCols` for the previous table, and that's what's causing this issue.  Your fix works, but it's still weird that we are calling `checkCols` on the stale set of drop columns.

Comment (jlapacik) [reply functions/transformations/schema_mutators.go]: After discussing with @aanthony1243 we decided that dropping a non-existent column should not be an error. So the `m.DropCols != nil` check has been removed and now we only check columns in the case of `keep`.

File: functions/transformations/schema_mutators.go [hunk 2]
```diff
@@ -206,20 +206,23 @@ func NewDropKeepMutator(qs flux.OperationSpec) (*DropKeepMutator, error) {
...
+		for c := range m.DropCols {
+			if err := checkCol(c, tableCols); err != nil {
```
[the remark this answers is not in the document]
Comment (jlapacik) [reply functions/transformations/schema_mutators.go]: @aanthony1243 this has been resolved. An error no longer occurs when one of the input tables does not have a column specified by `drop`.
